### ISSUE TITLE
Hint does nothing on Bandcamp's play/pause buttons

### ISSUE THREAD

**Issue by d125q** [lydell/LinkHints#10]
### URL

https://kashiwadaisuke.bandcamp.com/track/stella

### Screen shot

![Screenshot from 2019-12-30 10-00-24](https://user-images.githubusercontent.com/7765538/71574984-6f3a6300-2aeb-11ea-875e-a241559165fb.png)

### Description

Activating the play button's hint (`I`) doesn't do anything.  I expect it to click the button, i.e., start playing the song.  Pausing a song that's playing doesn't work either.

Weirdly, a click via `ClickFocusedElement` (removed in https://github.com/lydell/LinkHints/commit/089f8707e0914d13af7c646277a1e0fe28bd8764) used to work.

### Debug info

<details>
<summary>JSON</summary>

```json
{
  "version": "0.0.0",
  "browser": "firefox",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0",
  "browserInfo": {
    "name": "Firefox",
    "vendor": "Mozilla",
    "version": "73.0a1",
    "buildID": "20191229212642"
  },
  "platformInfo": {
    "os": "linux",
    "arch": "x86-64"
  },
  "storage.sync": {},
  "storage.local": {
    "tutorialShown": true
  },
  "language": "en-US",
  "layout": null
}
```

</details>

**Comment by lydell** [comment]
Thanks for the report! This should be fixed now.
