### ISSUE TITLE
Copying hinted things

### ISSUE THREAD

**Issue by d125q** [lydell/LinkHints#14]
### Problem

It would be really nice if I could use LinkHints to copy hinted things.  At the moment I can do <kbd>Alt + Shift + L</kbd> to select an element, then use my keyboard to open the context menu, and finally copy it.

I feel like this is a few key presses too many, and would like to work on a solution.

### Suggestion

My suggestion is to add an additional operation to <kbd>Alt + Shift + L</kbd> so that in addition to (or instead of – this is up for discussion) selecting the element, it also does a "do what I mean" copy: if it's an image, the link to the image is copied; if it's an `<a>` element, its `href` is copied; if it's text, the text is copied, etc.

This operation can be triggered when the hint is completed while holding <kbd>Alt</kbd>.

**Comment by lydell** [comment]
I’ve been thinking about this as well, but have never been able to make up my mind.

On Linux, I press the Menu key to bring up the context menu and have memorized the access key for ”Copy URL”. I use it seldomly enough that I’m not sure if it’s worth a separate shortcut.

But on mac there’s no menu key, and there I do occasionally miss being able to copy link hrefs with the keyboard.

I think I like the idea of using <kbd>Alt</kbd> in <kbd>Alt + Shift + L</kbd> to do it. Currently that opens links in a new tab (like in all other modes), but that’s not very useful.

**Comment by lydell** [comment]
I implemented a first version here: https://github.com/lydell/LinkHints/tree/copy-element

Feel free to try it out if you want!

**Comment by d125q** [comment]
That was fast!  Thank you so much!  It works really well on a first try, but I will of course be testing more and reporting any issues I run into.

**Comment by lydell** [comment]
I pushed a commit that flashes the copied element, to make it more clear that something actually happened. There’s plugins for Vim that do this on `y`, and the VSCode and Atom Vim plugins support it too. Let me know what you think!

**Comment by lydell** [comment]
As a last resort, the HTML is now copied if it has no text. Not sure yet if that’s helpful or not.

**Comment by lydell** [comment]
Pushed a tweak to the element flashing. Now it _always_ flashes using `invert(0.75)`, instead of trying to flash using text selection.

**Comment by d125q** [comment]
Thank you!  FWIW, so far everything’s been working great for me.

**Comment by lydell** [comment]
I can’t make up my mind if the current flash effect is good enough. What do you think? It seems to work quite well, but is a bit inconsistent in how visible the flash is depending on background color.

**Comment by d125q** [comment]
In my opinion, it is definitely sufficient.

**Comment by lydell** [comment]
Nice! I think I’ll make a release this weekend.

**Comment by lydell** [comment]
Released in 1.1.0. Thanks for the idea, testing and tweaks!

**Comment by brainwo** [comment]
Is this functionality removed? I tried `Alt` `Shift` `L` it seems to only select the element and not copying it to clipboard.

**Comment by lydell** [comment]
It is not removed. I tried it on your GitHub comment and it worked. Remember to hold `Alt` (`Ctrl` on macOS) when typing the last hint character.
