### ISSUE TITLE
Adding an "Editor mode"

### ISSUE THREAD

**Issue by Guppster** [lydell/LinkHints#20]
### Problem

I use an opensource web-based IDE called [CodeMirror](https://github.com/codemirror/codemirror) and was wondering if I can use LinkHints to jump to a word in the JS editor window.

Here is the feature in action: (AceJump plugin for Intellij IDEs)

![](https://cloud.githubusercontent.com/assets/175716/20177444/124fb534-a74d-11e6-8912-1d220ae27091.png)

### Suggestion

I was looking looking at the debug options part of LinkHints and saw I can change `ATTRIBUTES_CLICKABLE`, etc. 

All the CodeMirror text elements class start with `cm-*`. ex. `cm-variable`, `cm-keyword`
Is there anyway I can configure LinkHints to pickup on these elements and click on them? 

Here is a live demo where you can test: https://codemirror.net/demo/anywordhint.html

**Comment by Guppster** [comment]
Update: 
The text selection command (^⇧L) works for this case but theres too many hints.
Does "filter by text" feature work on the text selection command?

**Comment by lydell** [comment]
Hi!

I try to avoid site-specific stuff as much as possible (favoring code that works on any website). CodeMirror isn’t really site-specific, though – it’s on lots of pages and more “component-specific” (and definitely not a web standard). It might make sense to support it – I don’t know yet. I might make a branch to try it out.

I don’t think there’s a way to add hints to the different parts of the syntax highlighting through the debug options.

One thing you could try out if you want is to write a [user script](https://en.wikipedia.org/wiki/Userscript) to add attributes to `cm-*` elements that makes Link Hints consider them clickable.

> Does "filter by text" feature work on the text selection command?

Well, uhm … did you try it 😉 ? Yes – “filter by text” works there as well. Maybe you ran into a bug?

**Comment by lydell** [comment]
Added in [version 1.2.0](https://github.com/lydell/LinkHints/issues/1#issuecomment-907661610). Thanks for the suggestion!
