### ISSUE TITLE
Fix hints to page ids

### ISSUE THREAD

**Issue by blaggacao** [lydell/LinkHints#28]
I'm using linkhitns with a restaurant software, where for example I want to fix hints to certain stable clickables (menu, table numbers, etc) so that muscle memory, and in the case of tables mnemonic, benefits kick in.

How would I be able to hack LinkedHints to do what I want. It seems rather a complex piece of software (repo) and I would appreciate a pointer to the file / lines, I would have to look at.

Potentially, I would need to modify the DOM of a particular site, in order to inject hint classes and let LinkHints work.on those classes, then. That would be a very nice solution since I want to disable certain clickables completely or start numbering in higher order strings (like 3 digits for menu, 2 digits for tables and 1 digit for primary contextual.flow control like add dish, close table, send kitchen-receipt, open cash drawer, etc.)

**Comment by blaggacao** [comment]
I think I would get quite far with my use case if I was able to:

- contitionally on URL regex
- inject custom js via de UI
- set css classes and or attributes (`linkhint = "001"`) so that:
  - I can fix hints to a specific string value
  - I can mark clickables as exempt from hinting
  - fixed hint strings are blacklisted from automatic hinting

**Comment by lydell** [comment]
Hi!

Link Hints is not at all built for this use case.

> contitionally on URL regex, inject custom js via de LinkHints UI

This is exactly what Web Extensions are good for. To me it sounds like it will be much easier to create your own extension that focuses only on the restaurant software you use, than to try and understand all the complexity Link Hints has from trying to work with _all_ pages.

**Comment by blaggacao** [comment]
Ok thank you! That reads like a good piece of advice. Thanks!
