### ISSUE TITLE
Problem sending linkhint's shortcut keys via Autohotkey

### ISSUE THREAD

**Issue by joefiesta** [lydell/LinkHints#38]
### Steps to reproduce

set up an autohotkey  hotkey:
F7::   send, !j

### description

I use Autohotkey to do tons of stuff.  Since Linkhints doesn't allow me to setup  single key shortcuts (one must use a modifier), I have written AHK hotkeys to send the multiple keystrokes required by LinkHints.  Specifically--although amonst other--I define F7 as "send !j"   (sends ALT + j) and F8 as "send !l" (sends ALT + l).   This means I use the Linkhints defaults for "CLICK" and "Open In New Tab and Switch to it".  

This works fine in Firefox.  My hints appear, I type the hint and it follows the link.  

in Chrome, however, it does not work.  Hitting F7  does send the "Alt + J" keystrokes and the hints appear.  However, when I type the linkhint, nothing happens.  The window has lost focus.   If I now click (just about anywhere in the window) focus is restored and the hints are still there and now they work.  

In Chrome if I instead type the ALT + J myself, everything works fine and no focus is lost.  Sending ALT+J via AHK should be the same as typing ALT + J.   So, I am not sure if this is an Autohotkey issue, a Chrome issue or a Linkhints issue.

**Comment by lydell** [comment]
> I am not sure if this is an Autohotkey issue, a Chrome issue or a Linkhints issue

Neither do I, and unfortunately I don’t feel like looking into it. Sorry! If you come up with a way of proving that this is something LinkHints can do anything about, I’ll reopen.

**Comment by joefiesta** [comment]
sounds fair.  thanks
