### ISSUE TITLE
Version 1.1.2 request

### ISSUE THREAD

**Issue by jzyinq** [lydell/LinkHints#42]
Hi, it's the Vivaldi guy again ;) Could you release another patch version of your extension?

I got this weird behavior on `1.1.1` that something causes the whole hint map to stop working - I see the hint counter on the extension icon but they're not rendered on the website. If I restart the extension everything works well (for a while).

I installed the extension from Github and the problem was gone - it seems that those dependency updates you performed, later on, fixed that issue.

**Comment by lydell** [comment]
Hi! I plan to release a new version in a week or two

**Comment by lydell** [comment]
I’ve released [version 1.2.0](https://github.com/lydell/LinkHints/issues/1#issuecomment-907661610) now (currently waiting for review by Mozilla and Google).
