### ISSUE TITLE
Alt key not registered in latest Firefox on Manjaro Linux (unconfirmed)

### ISSUE THREAD

**Issue by PMunch** [lydell/LinkHints#44]
Trying to get back into the pattern of using LinkHints in my daily workflow. But to my dismay Alt-J didn't do anything. Checked my settings, tried re-installed, but to no avail. None of the shortcuts in LinkHints do anything.

### Steps to reproduce
Latest Firefox (94.0.1) on a Linux machine running Manjaro. LinkHints version 1.2.0.

1. Hit Alt-J

### Debug info

NOTE: I use Dvorak, but I've tried both the multiple layouts button, and switching between different keys. Still no dice.

```json
{
  "version": "1.2.0",
  "browser": "firefox",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0",
  "browserInfo": {
    "name": "Firefox",
    "vendor": "Mozilla",
    "version": "94.0.1",
    "buildID": "20211107062956"
  },
  "platformInfo": {
    "os": "linux",
    "arch": "x86-64"
  },
  "storage.sync": {
    "keys.Digit9": [
      "9",
      ")"
    ],
    "keys.Space": [
      " ",
      " "
    ],
    "keys.Period": [
      ".",
      "V"
    ],
    "keys.Backslash": [
      "<",
      "|"
    ],
    "keys.Semicolon": [
      "s",
      "S"
    ],
    "keys.Digit7": [
      "7",
      "/"
    ],
    "keys.Digit6": [
      "6",
      "&"
    ],
    "keys.Equal": [
      "\\",
      "`"
    ],
    "keys.IntlBackslash": [
      "ø",
      "Ø"
    ],
    "keys.Minus": [
      "-",
      "?"
    ],
    "keys.BracketLeft": [
      "'",
      "{"
    ],
    "keys.": [
      "æ",
      "Æ"
    ],
    "keys.Digit8": [
      "8",
      "("
    ],
    "keys.Digit2": [
      "2",
      "\""
    ],
    "keys.Digit4": [
      "4",
      "¤"
    ],
    "keys.Backspace": [
      "Backspace",
      "Backspace"
    ],
    "keys.Digit0": [
      "0",
      "="
    ],
    "keys.Slash": [
      "z",
      "Z"
    ]
  },
  "storage.local": {
    "tutorialShown": true
  },
  "language": "en-US"
}
```

**Comment by PMunch** [comment]
Just tried to change the shortcut, and pressing Alt+J only inputs J. So it seems like Alt isn't getting captured.

**Comment by lydell** [comment]
Hi! Link Hints works fine on Firefox 95.0b7 on macOS at least. I’ll try to test on Linux (Ubuntu) tonight.

Until then, could you try if using a shortcut involving some other modifier than Alt works?

**Comment by PMunch** [comment]
I can verify that changing it to `Ctrl+J` works, but overriding more of the shortcuts involves overriding the default Firefox ones such as `Ctrl+L` to go to the address bar.

**Comment by lydell** [comment]
Thanks! I meant trying with other modifiers as a test, not as a workaround. Maybe the problem is isolated to the Alt key. Does _any_ Alt+something combo work?

**Comment by PMunch** [comment]
Nothing works with the alt key, sorry if I didn't make that clear. Holding alt while setting a shortcut (e.g. `Alt+J`) just results in the letter (e.g. `J` in the above example).

**Comment by lydell** [comment]
I tried Link Hints 1.2.0 on Ubuntu 20.04 now. Alt-J and others seem to work!

Can you go to this keyboard event test page, press Alt-J (with Link Hints disabled) and post a screenshot of the results?

http://gdh1995.cn/vimium-c/keyboard-test.html

This is what it looks like to me:

![image](https://user-images.githubusercontent.com/2142817/141835158-10b8baf4-80f1-4332-b1b1-d34a4fb30b72.png)

**Comment by PMunch** [comment]
Can confirm that it works now, not sure what has changed though.

**Comment by gdh1995** [comment]
During my test, when `privacy.resistFingerprinting` is enabled on `about:config`, Firefox will hide the state of `Alt` key and send a fake `Shift=true` on letter keys when CapsLock is on.
