### ISSUE TITLE
Filter by text unclear in tutorial

### ISSUE THREAD

**Issue by nickvisut** [lydell/LinkHints#46]
### Steps to reproduce

1. Go to: https://lydell.github.io/LinkHints/tutorial.html#step-4
2. Type: 2001
3. Note that nothing is highlighted
4. Press: enter
4. I would expect "2001" to be highlighted and enter to open the toggle

### Screen shot
![link-hints-filter-by-text](https://user-images.githubusercontent.com/2823112/147837699-b5e5bac8-2126-4d50-943c-93fe1d14c675.png)

### Description

The filter by text feature, as described, seems to allow the user to input characters to partially match link text. Upon trying this [in the tutorial](https://lydell.github.io/LinkHints/tutorial.html#step-4) by typing "2001", nothing appears to happen. I would expect "2001" to be highlighted.

### Debug info

<details>
<summary>Debug info</summary>

```json
{
  "version": "1.2.0",
  "browser": "chrome",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
  "platformInfo": {
    "arch": "arm64",
    "nacl_arch": "arm",
    "os": "mac"
  },
  "storage.sync": {},
  "storage.local": {
    "tutorialShown": true
  },
  "language": "en-US",
  "layout": {
    "KeyE": "e",
    "KeyD": "d",
    "Minus": "-",
    "KeyH": "h",
    "KeyZ": "z",
    "Equal": "=",
    "KeyN": "n",
    "KeyP": "p",
    "BracketRight": "]",
    "BracketLeft": "[",
    "Digit8": "8",
    "Digit9": "9",
    "KeyS": "s",
    "Semicolon": ";",
    "Digit5": "5",
    "KeyQ": "q",
    "KeyO": "o",
    "Period": ".",
    "Digit6": "6",
    "KeyV": "v",
    "Digit3": "3",
    "KeyL": "l",
    "Backquote": "`",
    "KeyG": "g",
    "KeyJ": "j",
    "KeyT": "t",
    "Quote": "'",
    "KeyY": "y",
    "IntlBackslash": "§",
    "KeyR": "r",
    "Backslash": "\\",
    "KeyU": "u",
    "KeyK": "k",
    "Slash": "/",
    "KeyF": "f",
    "KeyI": "i",
    "KeyX": "x",
    "KeyA": "a",
    "Digit2": "2",
    "Digit7": "7",
    "KeyM": "m",
    "Digit4": "4",
    "KeyW": "w",
    "Digit1": "1",
    "Digit0": "0",
    "KeyB": "b",
    "KeyC": "c",
    "Comma": ","
  }
}
```

</details>

**Comment by lydell** [comment]
Hi! What is the “two zero zero one” and “enter” things in the bottom right?

**Comment by nickvisut** [comment]
Hello! That is talonvoice.com which I use due to RSI.

I’ve also tested with keyboard, however.

**Comment by lydell** [comment]
Do you use Vimium (or some other Vim-for-browser plugin) by any chance? It “steals” digit presses for its count feature.

If not:

- Can you filter by other chars than digits, such as letters? (Hold shift.)
- Do you use any other keyboard related extensions or programs?

**Comment by nickvisut** [comment]
Thanks for the questions/tips. I was using vimium in Chrome before, but I
disabled it because I was looking for an extension that had persistent
hints. I double checked that it wasn’t running and also tested in a profile
with minimal extensions; also ran it in FF).

I tried letters with shift and no luck either.

Upon your suggestion, I disabled or uninstalled all apps I could think of
that monitor keyboard input and that didn’t seem to help either. FWIW I’m
on an M1 Mac on MacOS Monterey.

**Comment by lydell** [comment]
Thanks for your investigation!

I use a mac myself, but not an M1. Maybe things don’t work on M1, I don’t know. I’m out of ideas.

> I was looking for an extension that had persistent hints

Note that Link Hints does not have persistent hints either (if I understand what you mean by “persistent”) – Link Hints’ hints are very similar to Vimium.

**Comment by lydell** [comment]
Ok, one more idea. You say “Filter by text not working _in tutorial_”. Is it only in the tutorial that it doesn’t work?

**Comment by nickvisut** [comment]
It appears to not work anywhere, unfortunately. Do you think it's the M1?

As for Link Hints not having persistent hints, is that something you had
consider adding? Pretty helpful in cases where someone will be using link
hints almost exclusively to navigate. Saves more keypresses than you might
imagine. It is partially persistent due to the "Click many" and "Open many
tabs", which is one reason I'm using it over Vimium.

**Comment by lydell** [comment]
> Do you think it's the M1?

It could be. But I have no idea what’s going on on your computer, really. It’s so weird that it simply does not work at all, while shortcuts and typing hints work. Sounds impossible! 🤯 

> As for Link Hints not having persistent hints, is that something you had consider adding?

If you mean that hints should be visible at all times for all clickable things – I can’t even imagine how that would work.

- My first thought is to give hints to _all_ elements on the page, not just the ones visible on screen. Problems:
  - All hints become longer.
  - Slower.
  - What to do when more clickable elements appear? There might not be enough hints left (remember, they are prefix codes). One could anticipate that by making all hints _even longer_ from the start to have more “space” left, to some degree. Or one needs to recalculate all hints when new elements appear. But then they might change just before you were going to type one of them, and suddenly you’ve clicked something other than you intended.
- Another idea is to recalculate all hints as you scroll. But it will feel pretty janky. If you’ve ever tried scrolling while having the hints up in Link Hints – that’s kind of what it will look like.
- Another downside is that I poll all hinted elements for their position every second or so, to move the hint if the element moves. That would be battery draining if you ran it all the time.

The more I think about it, some kind of persistent hints feels like a completely different feature with different problems needing to be solved. It’s not something I’m interested in.

**Comment by lydell** [comment]
I was finally able to test on an M1 Mac today! Filter by text works though, including in the tutorial.

I noticed one step is missing in your steps to reproduce though (never noticed before):

1. Go to: https://lydell.github.io/LinkHints/tutorial.html#step-4
2. **Press <kbd data-mac="Ctrl" title="Control">^</kbd><kbd>J</kbd>** _this was missing!_
3. Type: 2001
4. Note that nothing is highlighted
5. Press: enter
4. I would expect "2001" to be highlighted and enter to open the toggle

So maybe the tutorial has simply been unclear this whole time?
