### ISSUE TITLE
Use the managed storage

### ISSUE THREAD

**Issue by p1llule** [lydell/LinkHints#47]
### Problem

The settings of your extension can be imported and exported but not managed automatically.

### Suggestion

Use browser.managed.get

[You can learn more in this article](https://blog.mozilla.org/addons/2017/09/28/webextensions-in-firefox-57/), section Storage API

**Comment by lydell** [comment]
Hi! Can you elaborate on your use case?

**Comment by p1llule** [comment]
I try to have a firefox configuration that I can deploy in my virtual machines. Theses virtual machines are renewed regularly and setting up all my add-ons options each time would be a chore so I use some scripts and features of firefox to avoid it as much as I can.

I can install all the extensions I want with a policies.json but to set their options is often a problem. The only extension I use and manage with the storage API right now is µBlock origin.

I like link hints but I have two things to setup with it : I am a colemak user, and use the configuration resistFingerprinting (with firefox 91.4.1 esr, that setting does not allow me to use the alt modifier with your extension, that would be nice if that wasn't targeting linkhint but that is another topic).

Anyway thank you for link hints ;)

**Comment by lydell** [comment]
Thanks! I read about it some more. At least for Firefox it looks pretty easy:

Try to read from `storage.managed`. If that fails with “Managed storage manifest not found”, read from `storage.sync` instead like today. Might need to listen for change events from `storage.managed` too. And figure out how the options UI should behave (it still has to write to `storage.sync` I guess?). (Chrome looks more complicated and not worth it.)

Does that sound correct to you?

**Comment by lydell** [comment]
Hi again! I’ve decided in the end that this is not something I want to spend time on.

**Comment by p1llule** [comment]
That's fine, have fun.
