### ISSUE TITLE
Link Hints Stopped Appearing

### ISSUE THREAD

**Issue by mymil** [lydell/LinkHints#51]
### Steps to reproduce

These reproduce the error for me, but probably not for you:

1. Go to: https://lydell.github.io/LinkHints/
2. Press Alt+J

### Screen shot

![image](https://user-images.githubusercontent.com/33109970/160172654-2ee46841-f798-4160-be03-c425142c220e.png)

### Description

After using any Link Hint keyboard trigger, no hints display. However, the extension icon shows a count of hints (see screen shot), and the hinted links can be accessed by typing letters. (Unpredictably, because the hints themselves are not displaying.)

This bug happens seemingly on every page. Until recently, Link Hints worked perfectly. I don't know what changed. I haven't encountered any conflicts with any of the other extensions I've been using.

### Debug info

<details>
<summary>Debug info</summary>

```json
{
  "version": "1.2.0",
  "browser": "chrome",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36",
  "platformInfo": {
    "arch": "x86-64",
    "nacl_arch": "x86-64",
    "os": "win"
  },
  "storage.sync": {},
  "storage.local": {
    "tutorialShown": true
  },
  "language": "en-US",
  "layout": {
    "KeyE": "e",
    "KeyD": "d",
    "Minus": "-",
    "KeyH": "h",
    "KeyZ": "z",
    "Equal": "=",
    "KeyN": "n",
    "KeyP": "p",
    "BracketRight": "]",
    "BracketLeft": "[",
    "Digit8": "8",
    "Digit9": "9",
    "KeyS": "s",
    "Semicolon": ";",
    "Digit5": "5",
    "KeyQ": "q",
    "KeyO": "o",
    "Period": ".",
    "Digit6": "6",
    "KeyV": "v",
    "Digit3": "3",
    "KeyL": "l",
    "Backquote": "`",
    "KeyG": "g",
    "KeyJ": "j",
    "KeyT": "t",
    "Quote": "'",
    "KeyY": "y",
    "IntlBackslash": "\\",
    "KeyR": "r",
    "Backslash": "\\",
    "KeyU": "u",
    "KeyK": "k",
    "Slash": "/",
    "KeyF": "f",
    "KeyI": "i",
    "KeyX": "x",
    "KeyA": "a",
    "Digit2": "2",
    "Digit7": "7",
    "KeyM": "m",
    "Digit4": "4",
    "KeyW": "w",
    "Digit1": "1",
    "Digit0": "0",
    "KeyB": "b",
    "KeyC": "c",
    "Comma": ","
  }
}
```

</details>

**Comment by lydell** [comment]
Hi!

Thanks for the very nice report! Really odd issue.

As you guessed, I’m not experiencing this myself, in neither Chrome nor Firefox.

Have you (or @PhilipRoman, you 👍  the issue), ever used the [Chrome Developer Tools Inspector](https://developer.chrome.com/docs/devtools/overview/#elements) by any chance? When you have activated hints, at the very bottom of the panel you should be able to inspect the elements for the hints:

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/2142817/160240483-d0ee2e8d-5623-4553-91aa-a26e1abece09.png">

I’m curious what you’ll find there. Are there any hint elements at all there? If yes, are they invisible?

That’s the only thing I can think of in terms of debugging right now.

**Comment by PhilipRoman** [comment]
There are no hint elements in DOM, but there is an error message in console:
```
Uncaught ReferenceError: browser is not defined
    at tweakable (chrome-extension://kjjgifdfplpegljdfnpmbjmkngdilmkd/renderer.js:824:20)
    at chrome-extension://kjjgifdfplpegljdfnpmbjmkngdilmkd/renderer.js:896:3
    at chrome-extension://kjjgifdfplpegljdfnpmbjmkngdilmkd/renderer.js:1725:3
```
(the extension id matches Link Hints)

**Comment by lydell** [comment]
Interesting, thanks!

`browser` is supposed to exist, because of `browser-polyfill.js`. As you can see, the error comes from `renderer.js`. Maybe Chrome has stopped loading all the content scripts in order? If `renderer.js` loads _before_ the others it’s not gonna work.

```json
  "content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "all_frames": true,
      "match_about_blank": true,
      "run_at": "document_start",
      "js": [
        "browser-polyfill.js",
        "worker.js"
      ]
    },
    {
      "matches": [
        "<all_urls>"
      ],
      "run_at": "document_start",
      "js": [
        "renderer.js"
      ]
    }
  ]
```

**Comment by PhilipRoman** [comment]
I can confirm after setting breakpoints that `renderer.js` runs before polyfill

**Comment by lydell** [comment]
Thanks! One solution could be to put `browser-polyfill.js` both before `worker.js` and before `renderer.js`. Hopefully loading it twice in the top frame won’t matter.

**Comment by lydell** [comment]
[Version 1.2.3](https://github.com/lydell/LinkHints/issues/1#issuecomment-1079900548) loads the browser polyfill twice, which hopefully should fix the problem. It should be available on the Chrome Web Store in ~2 months.

If you’re feeling adventurous and would like to build Link Hints yourselves in the mean time, check out [Local installation](https://github.com/lydell/LinkHints/blob/main/CONTRIBUTING.md#installation).

**Comment by budRich** [comment]
I just got the last version and noticed that when trying to load the "*dev*" version (loading unpacked compiled directory) in vivaldi, i got errors about the same **browser not defined**, these errors showed up immediately on the plugin load page, and LinkHints didn't load at all. The generated .crx does work fine.

**Comment by lydell** [comment]
I also get that error immediately (in background.js), but it doesn’t seem to matter: Everything worked anyway.

**Comment by budRich** [comment]
yeah, got it working now. i had only done `npm test`, after `npm run watch` the unpacked version worked fine.

**Comment by mymil** [comment]
Thank you for the super fast fix! I'll hold off on installing on my employer-managed machine until it's in the chrome store. Thanks again!

**Comment by mymil** [comment]
It works! Thanks again! 🎉
