### ISSUE TITLE
Redundant hint on Github diff pages

### ISSUE THREAD

**Issue by the-blank-x** [lydell/LinkHints#72]
### URL

https://github.com/lydell/LinkHints/commit/83240d89df4120fe3746cd3a30568f0fd9eded65

### Screen shot

![](https://user-images.githubusercontent.com/45762106/234308509-97db61f2-f2ab-421f-98a9-2fd48451340e.png)

### Description

On any page on Github showing a diff with more than one file (e.g. the link above), files and collapsed directories contain a redundant hint that does nothing.
I believe I've found out what causes this: a `li` element with a `role=treeitem` attribute that contains a `button` or `a` element. There are two hints overlaid on top of each other: one for the `li` element, which does nothing, and one for the `button` or `a` element, which actually goes to a diff or opens/closes a directory. I've made an example webpage that demonstrates this: [t.html.gz](https://github.com/lydell/LinkHints/files/11323476/t.html.gz).
I'm unsure if elements with a `treeitem` role should be treated as any other ordinary element [since they might be used on other sites](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/), or if this can be fixed generically (i.e. not writing website-specific code).

### Debug info

<details>
<summary>Debug info</summary>

```json
{
  "version": "1.3.1",
  "browser": "firefox",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:111.0) Gecko/20100101 Firefox/111.0",
  "browserInfo": {
    "name": "Firefox",
    "vendor": "LibreWolf",
    "version": "111.0.1",
    "buildID": "20230325152712"
  },
  "platformInfo": {
    "os": "linux",
    "arch": "x86-64"
  },
  "storage.sync": {
    "normal.ctrl-j": "EnterHintsMode_Click",
    "normal.ctrl-k": "EnterHintsMode_BackgroundTab",
    "normal.ctrl-J": "EnterHintsMode_ManyClick",
    "normal.ctrl-K": "EnterHintsMode_ManyTab",
    "normal.ctrl-L": "EnterHintsMode_Select",
    "normal.ctrl-:": "EnterHintsMode_ForegroundTab"
  },
  "storage.local": {
    "tutorialShown": true
  },
  "language": "en-US"
}
```

</details>

**Comment by lydell** [comment]
I’ve noticed those too! Pretty annoying for sure.

**Comment by lydell** [comment]
For now, you can:

1. Open the Link Hints Options page.
2. Scroll to the very bottom.
3. Expand the “Debug” section.
4. Remove `treeitem` from this section:

   <img width="819" alt="image" src="https://user-images.githubusercontent.com/2142817/234476111-d1f9c766-76ef-4984-803f-205081c3df62.png">
5. Reload the GitHub page you’re testing on.
