### ISSUE TITLE
Absolute links with fragments and relative links may have different or no hints

### ISSUE THREAD

**Issue by the-blank-x** [lydell/LinkHints#74]
### Steps to reproduce

1. Decompress [t.html.gz](https://github.com/lydell/LinkHints/files/11413074/t.html.gz)
2. Either open the page via the file:// URI, or start a file server and open it that way
3. Activate Click hints, or activate Open link in new tab hints

### Screen shot

**On file://**
Click:
![](https://user-images.githubusercontent.com/45762106/236640711-219c7b0f-3d52-4450-b52f-24647c6501b4.png)
Open link in new tab:
![](https://user-images.githubusercontent.com/45762106/236640715-9393dd88-ce0c-4464-99d8-69f5aaafb6eb.png)

**On http://:**
Click:
![](https://user-images.githubusercontent.com/45762106/236640716-3c3af0ca-3c33-428c-a41f-d725d81d4a25.png)

### Description

**On file://:**
- If you activate the Click hints mode, absolute links with fragments and relative links have different hints.
- if you activate the Open link in new tab mode, relative links do not have hints, but absolute links with fragments do have the same hint.

**On http://:**
- If you activate the Click hints mode, links with fragments have different hints.

### Debug info

<details>
<summary>Debug info</summary>

```json
{
  "version": "1.3.1",
  "browser": "firefox",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:112.0) Gecko/20100101 Firefox/112.0",
  "browserInfo": {
    "name": "Firefox",
    "vendor": "LibreWolf",
    "version": "112.0.2-1",
    "buildID": "20230430120954"
  },
  "platformInfo": {
    "os": "linux",
    "arch": "x86-64"
  },
  "storage.sync": {
    "normal.ctrl-j": "EnterHintsMode_Click",
    "normal.ctrl-k": "EnterHintsMode_BackgroundTab",
    "normal.ctrl-J": "EnterHintsMode_ManyClick",
    "normal.ctrl-K": "EnterHintsMode_ManyTab",
    "normal.ctrl-L": "EnterHintsMode_Select",
    "normal.ctrl-:": "EnterHintsMode_ForegroundTab",
    "debug.Background.PREFER_WINDOWS": false,
    "debug.ElementManager.ROLES_CLICKABLE": [
      "button",
      "checkbox",
      "link",
      "menuitem",
      "menuitemcheckbox",
      "menuitemradio",
      "option",
      "radio",
      "searchbox",
      "spinbutton",
      "switch",
      "tab",
      "textbox"
    ],
    "hints.ctrl-Enter": "ActivateHintAlt",
    "debug.ElementManager.ATTRIBUTES_CLICKABLE": [
      "aria-checked",
      "aria-selected",
      "data-dismiss",
      "data-ember-action",
      "data-image-url",
      "data-line-number",
      "data-permalink-path"
    ]
  },
  "storage.local": {
    "tutorialShown": true
  },
  "language": "en-US"
}
```

</details>

**Comment by lydell** [comment]
Firefox is unfortunately very restrictive on the `file:` protocol: https://github.com/lydell/LinkHints/commit/ba65c47f9c6795c444d72f647d0ca88cf705a235

At least it was 5 years ago. That’s part of it.

**Comment by lydell** [comment]
Following the spec, we should use the same hint for the same fragment. But unfortunately that does not work in practice:

https://github.com/lydell/LinkHints/blob/495652ec888fea99526eaf3fd3b679f03819302e/html/combine-hrefs/index.html#L58-L96

**Comment by lydell** [comment]
This issue feels a bit “academic” – more like the types of experiments I did while developing to try to understand problems from all angles. I appreciate your other two issues more since they are driven by very clear use cases.

**Comment by the-blank-x** [comment]
Makes sense, I encountered a page with two links with the same fragment that has different hints and that made me wonder why.

**Comment by lydell** [comment]
I don’t think there’s anything to do in this issue.
