### ISSUE TITLE
Missing hint on Wayback Machine calendar

### ISSUE THREAD

**Issue by the-blank-x** [lydell/LinkHints#75]
### URL

https://web.archive.org/web/20230601000000*/http://es.smashbros.wikia.com/wiki/Hilo:87131

### Screen shot

![](https://github.com/lydell/LinkHints/assets/45762106/e9f38488-9ad6-4606-b163-ff903b7f89f7)

### Description

If you activate hints on a calendar page, there are no hints for the year labels. It seems like this can be fixed by treating elements with `sparkline-year-label` class as a clickable element.

### Debug info

<details>
<summary>Debug info</summary>

```json
{
  "version": "1.3.1",
  "browser": "firefox",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:112.0) Gecko/20100101 Firefox/112.0",
  "browserInfo": {
    "name": "Firefox",
    "vendor": "LibreWolf",
    "version": "112.0.2-1",
    "buildID": "20230430120954"
  },
  "platformInfo": {
    "os": "linux",
    "arch": "x86-64"
  },
  "storage.sync": {
    "normal.ctrl-j": "EnterHintsMode_Click",
    "normal.ctrl-k": "EnterHintsMode_BackgroundTab",
    "normal.ctrl-J": "EnterHintsMode_ManyClick",
    "normal.ctrl-K": "EnterHintsMode_ManyTab",
    "normal.ctrl-L": "EnterHintsMode_Select",
    "normal.ctrl-:": "EnterHintsMode_ForegroundTab",
    "debug.Background.PREFER_WINDOWS": false,
    "debug.ElementManager.ROLES_CLICKABLE": [
      "button",
      "checkbox",
      "link",
      "menuitem",
      "menuitemcheckbox",
      "menuitemradio",
      "option",
      "radio",
      "searchbox",
      "spinbutton",
      "switch",
      "tab",
      "textbox"
    ],
    "hints.ctrl-Enter": "ActivateHintAlt",
    "debug.ElementManager.ATTRIBUTES_CLICKABLE": [
      "aria-checked",
      "aria-selected",
      "data-dismiss",
      "data-ember-action",
      "data-image-url",
      "data-line-number",
      "data-permalink-path"
    ]
  },
  "storage.local": {
    "tutorialShown": true
  },
  "language": "en-US"
}
```

</details>

**Comment by lydell** [comment]
I probably won’t add something as site specific as `sparkline-year-label`, but you can experiment with adding it to the `REGEX_CLICKABLE_CLASS` option.

**Comment by the-blank-x** [comment]
Fair enough, do I close this?

**Comment by lydell** [comment]
Yes, let’s close it. Those year labels aren’t accessible at all. If you have the energy, you could contact Wayback Machine and ask them to make the year labels accessible to keyboard users (can’t even tab to them).
