### ISSUE TITLE
Support <details> without <summary>

### ISSUE THREAD

**Issue by the-blank-x** [lydell/LinkHints#77]
### URL

The bottom of the comment in https://tildes.net/~games/160b/any_android_games_that_are_worth_playing_these_days#comment-85o1  
https://tildes.net/~talk/145a/unpopular_opinion_wikipedias_old_look_was_much_better_than_the_new_one#comment-7ovd

### Screenshot

![](https://github.com/lydell/LinkHints/assets/45762106/1dab111d-1ebd-46b8-81c3-690863d82324)

### Description

Whenever a &lt;details&gt; element with no &lt;summary&gt; is encountered, Link Hints does not add a hint to the default "Details" text of the element. I can also reproduce it here: [t.html.gz](https://github.com/lydell/LinkHints/files/11714979/t.html.gz)

### Debug info

<details>
<summary>Debug info</summary>

```json
{
  "version": "1.3.1",
  "browser": "firefox",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:113.0) Gecko/20100101 Firefox/113.0",
  "browserInfo": {
    "name": "Firefox",
    "vendor": "LibreWolf",
    "version": "113.0.2-1",
    "buildID": "20230531125735"
  },
  "platformInfo": {
    "os": "linux",
    "arch": "x86-64"
  },
  "storage.sync": {
    "normal.ctrl-j": "EnterHintsMode_Click",
    "normal.ctrl-k": "EnterHintsMode_BackgroundTab",
    "normal.ctrl-J": "EnterHintsMode_ManyClick",
    "normal.ctrl-K": "EnterHintsMode_ManyTab",
    "normal.ctrl-L": "EnterHintsMode_Select",
    "normal.ctrl-:": "EnterHintsMode_ForegroundTab",
    "debug.Background.PREFER_WINDOWS": false,
    "debug.ElementManager.ROLES_CLICKABLE": [
      "button",
      "checkbox",
      "link",
      "menuitem",
      "menuitemcheckbox",
      "menuitemradio",
      "option",
      "radio",
      "searchbox",
      "spinbutton",
      "switch",
      "tab",
      "textbox"
    ],
    "hints.ctrl-Enter": "ActivateHintAlt",
    "debug.ElementManager.ATTRIBUTES_CLICKABLE": [
      "aria-checked",
      "aria-selected",
      "data-dismiss",
      "data-ember-action",
      "data-image-url",
      "data-line-number",
      "data-permalink-path"
    ],
    "debug.ElementManager.REGEX_CLICKABLE_CLASS": "\\bcm-|ͼ|\\bmtk|sparkline-year-label|js-wiki-toggle-collapse"
  },
  "storage.local": {
    "tutorialShown": true
  },
  "language": "en-US"
}
```

</details>

**Comment by lydell** [comment]
TIL:

- [The HTML specification for `<details>`](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element) requires the `<summary>` element to be present, but still defines how user agents should deal with a missing summary:

  > The first [summary](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element) element child of the element, if any, [represents](https://html.spec.whatwg.org/multipage/dom.html#represents) the [summary](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element) or legend of the details. If there is no child summary element, the user agent should provide its own legend (e.g. "Details").

- That sites actually rely on this.

Test case:

<details>

stuff

</details>
