### ISSUE TITLE
Drill-down approach for selecting among too many links/elements

### ISSUE THREAD

**Issue by george-tsiros** [lydell/LinkHints#78]
(Terceness is intentional.)

Difficulty: Some webpages have too many links.

Suggestion: Mark a website by "region", pressing the associated character key selects that region and, only then, shows the key-hints for that region only.

instead of directly showing all choices available
![currently](https://github.com/lydell/LinkHints/assets/54522275/2e48d8d6-a7e0-4cbd-bfed-470dec7cdbbd)
first, show only regions:
![suggestion](https://github.com/lydell/LinkHints/assets/54522275/32a0f90e-136b-48d1-ade3-68dd4caf2414)

I fully understand this may be downright impossible considering how convoluted html has become these days

**Comment by lydell** [comment]
Hi!

This is a very interesting feature idea!

However, I’m happy with Link Hints as is, and I don’t have much time to spend on it these days.

This is a pretty large thing. I think the best course of action would be to fork Link Hints and do it as a new, different extension. Or even start from scratch and only using the Link Hints code as inspiration.

**Comment by george-tsiros** [comment]
Thank you for your kind words and thank you for this very, very useful tool
