### ISSUE TITLE
Add web support

### ISSUE THREAD

**Issue by alexherbo2** [lydell/LinkHints#8]
It would be cool if Link Hints could be used as a module (with CDN support) without a browser extension.

**Comment by alexherbo2** [comment]
Web support would be cool if I don’t want to lose the [live demo] on [Krabby].

Added to that, you could have your own live demo.

[Krabby]: https://krabby.netlify.com
[Live demo]: https://krabby.netlify.com#live-demo

**Comment by lydell** [comment]
I’ve decided not to do this.
