### ISSUE TITLE
Hints appear blacker on Libreboot's website

### ISSUE THREAD

**Issue by the-blank-x** [lydell/LinkHints#82]
### Steps to reproduce

1. Go to https://libreboot.org/
2. Activate hints

### Screen shot

![](https://github.com/lydell/LinkHints/assets/45762106/de1c5405-6720-44c9-9e53-f632ee82a75f)

### Description

Hints look blacker/bolder than normal on the Libreboot website. It seems like this is due to a `text-shadow: 1px 1px #000` on the page. Adding `.root { text-shadow: none; }` or `.root { text-shadow: initial; }` into Link Hints' CSS overrides section seems to remedy this

### Debug info

<details>
<summary>Debug info</summary>

```json
{
  "version": "1.3.1",
  "browser": "firefox",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
  "browserInfo": {
    "name": "Firefox",
    "vendor": "LibreWolf",
    "version": "115.0.2-2",
    "buildID": "20230712143257"
  },
  "platformInfo": {
    "os": "linux",
    "arch": "x86-64"
  },
  "storage.sync": {
    "normal.ctrl-j": "EnterHintsMode_Click",
    "normal.ctrl-k": "EnterHintsMode_BackgroundTab",
    "normal.ctrl-J": "EnterHintsMode_ManyClick",
    "normal.ctrl-K": "EnterHintsMode_ManyTab",
    "normal.ctrl-L": "EnterHintsMode_Select",
    "normal.ctrl-:": "EnterHintsMode_ForegroundTab",
    "debug.Background.PREFER_WINDOWS": false,
    "debug.ElementManager.ROLES_CLICKABLE": [
      "button",
      "checkbox",
      "link",
      "menuitem",
      "menuitemcheckbox",
      "menuitemradio",
      "option",
      "radio",
      "searchbox",
      "spinbutton",
      "switch",
      "tab",
      "textbox"
    ],
    "hints.ctrl-Enter": "ActivateHintAlt",
    "debug.ElementManager.ATTRIBUTES_CLICKABLE": [
      "aria-checked",
      "aria-selected",
      "data-dismiss",
      "data-ember-action",
      "data-image-url",
      "data-line-number",
      "data-permalink-path"
    ],
    "debug.ElementManager.REGEX_CLICKABLE_CLASS": "\\bcm-|ͼ|\\bmtk|sparkline-year-label|js-wiki-toggle-collapse",
    "hints.shift-Backspace": "Backspace",
    "hints.shift-Enter": "ActivateHint"
  },
  "storage.local": {
    "tutorialShown": true
  },
  "language": "en-US"
}
```

</details>

**Comment by lydell** [comment]
Interesting! Shadow roots are supposed to protect against CSS like this. Maybe there’s a bug in Firefox!

**Comment by the-blank-x** [comment]
Looks like `line-height`, `text-align`, `font-size`, `background-color`, and `color` can "seep in" to a page: 
[css-into-shadow-root.html.gz](https://github.com/lydell/LinkHints/files/12212711/css-into-shadow-root.html.gz)

**Comment by lydell** [comment]
Thanks!

This article explains what I have misunderstood about shadow DOM the whole time: https://lamplightdev.com/blog/2019/03/26/why-is-my-web-component-inheriting-styles/

The should be the solution:

```diff
 .root {
+  all: initial;
   font: menu;
 }
```

Until that is fixed, you can add it yourself in the options.

**Comment by the-blank-x** [comment]
Interesting! It seems like adding it in Firefox causes some funky behavior though

https://github.com/lydell/LinkHints/assets/45762106/aa82be4d-13a8-4904-9720-cc88065e2446
