### ISSUE TITLE
Why not use `all: unset !important;` for the hints parent element with id `__LinkHintsWebExt` ?

### ISSUE THREAD

**Issue by heiwiper** [lydell/LinkHints#90]
In Nyxt Browser the hints are added inside the element `body` before the end, I'm looking to move all the hints in a parent element that is a sibling of `body`, similar to how you do it in LinkHints. I had some styling issue after I did that so I tried to replicate the styling you are using for the hints parent element. I noticed how you unset many style properties for the parent which actually solved my problem when I applied it, but I'm curious to why not unset the property `all` instead of unsetting many properties one by one ?

I would also like to take the chance to thank you for your Addon, I've been using it on Firefox since around 3 years. Now I'm also using it as an inspiration to replicate some functionalities on Nyxt Browser.

**Comment by lydell** [comment]
Hi! That’s exactly what I do:

https://github.com/lydell/LinkHints/blob/495652ec888fea99526eaf3fd3b679f03819302e/src/shared/css.ts#L20

Note that both Chrome’s and Firefox’s devtools doesn’t show `all: unset` when you inspect the element, they instead show what it “expands” to – which is quite a few properties :)

**Comment by heiwiper** [comment]
Oh I see, that makes sense now. I'm very grateful to you for your quick response :D
